general:
  github_repo_url: "https://github.com/2404589803/hf-daily-paper-newsletter-chinese"
  git_branch: "main"

email:
  title: "ğŸ¤— æ¯æ—¥è®ºæ–‡"
  footer_title: "å¸Œæœ›åœ¨è¿™æ‚¨å¯ä»¥å‘ç°æ‚¨èƒ½ç”¨åˆ°çš„æœ‰è¶£ä¿¡æ¯"
  receivers:
    - qgesx2003123@163.com
    - jimt40395@gmail.com
  header_title: "ğŸ¤— æ¯æ—¥è®ºæ–‡"
  header_description: "ç¥æ‚¨é˜…è¯»æ„‰å¿«ï¼"
  header_image_url: "https://i.ibb.co/1Gx4TF7/Screenshot-2024-01-13-at-8-51-14-PM.png"
  community_link: "https://github.com/2404589803/hf-daily-paper-newsletter-chinese"
  community_link_btn_title: "ğŸ¤— æ¯æ—¥è®ºæ–‡é¡¹ç›®"
  section_title: "æŸ¥çœ‹é¡¹ç›®é¡µé¢ä»¥è·å–æ›´æœ‰æ¡ç†çš„è®ºæ–‡åˆ—è¡¨"
  content_link_btn_title: "é˜…è¯»å…¨æ–‡"
  bgcolor: "orange"